### ISSUE TITLE
Investigate- Support for iOS 11

### ISSUE THREAD

**Issue by at-aoiyamamura** [netprotections/atonecon-ios#104]
### Summary (Required)
Support for iOS 11

### Description (Required)
iOS 11 has already released. Please test and investigate whether there is no problem.
If there is any problem, can you tell me?
If there is no problem, I will close this issue.

**Comment by at-thinhung** [comment]
@at-aoiyamamura 
There is no problem with iOS 11

**Comment by at-diemnguyen** [comment]
@at-duyentran E check library trên iOS11 chưa? Và có vấn đề gì k?
E report vào đây giúp c nhé.

**Comment by at-duyentran** [comment]
@at-aoiyamamura @at-diemnguyen I checked library on IOS 11 and don't found problem

**Comment by at-aoiyamamura** [comment]
@at-duyentran @at-thinhung 
So far, I will close this issue 
@at-duyentran 
If you find any bugs on iOS 11, please make new issue.
