### ISSUE TITLE
Atone Form: Missing requested time out message when can not connect to server

### ISSUE THREAD

**Issue by at-kiennguyen2** [netprotections/atonecon-ios#50]
### Summary (Required)
Missing requested time out message when can not connect to server

### Description (Required)
1. Perform a transaction with internet connection weak or low respond from server
2. Wait for a long time

Actual result: Missing requested time out message when can not connect to server

### Acceptance Criteria (Optional)

Requested time out message must be displayed when can not connect to server (Maximum should be 60s)

**Comment by at-duyentran** [comment]
@at-aoiyamamura 
Waiting for client's check

**Comment by at-diemnguyen** [comment]
Cái này Hoài đã fix, a Kiên đã check Ok rồi. Giờ chờ client check OK sẽ close.

**Comment by at-diemnguyen** [comment]
@at-aoiyamamura

**Comment by at-aoiyamamura** [comment]
@at-duyentran @at-thinhung @at-hanhpham 
We do not have any feedback from client about this issue.
iOS side already resolved, so I will close this issue. Sorry for late.
