### ISSUE TITLE
Atone Form: Keyboard should be closed automatic after user inputs wrong Passcode

### ISSUE THREAD

**Issue by at-kiennguyen2** [netprotections/atonecon-ios#61]
### Summary (Required)
- After input wrong passcode, Error message will be displayed behind the keyboard and user can't know what are happening. So, i want to suggest to close Keyboard automation after user inputs wrong Passcode

### Description (Required)
1. Go to Passcode screen
2. Input wrong Passcode

Actual result: Error message will be displayed behind the keyboard and user can't know what are happening.

### Acceptance Criteria (Optional)
- Keyboard should be closed automatic after user inputs wrong Passcode.

### References (Optional)
- Please refer Android issue https://github.com/AsianTechInc/AtoneCon-Android/issues/54

**Comment by at-duyentran** [comment]
@at-aoiyamamura
When having new information about this bug, please help to update it

**Comment by at-aoiyamamura** [comment]
@at-diemnguyen 
クライアントが、it環境にフォーカスアウトの対応を入れました。
スマホでもキーボードのフォーカスがはずれエラーメッセージが確認できるかテストしていただければと思います。

**Comment by at-diemnguyen** [comment]
@at-duyentran Client đã fix bug này rồi.
Thêm xử lý focus out.
Bên mình check lại keyboard đã được focus out chưa và có hiển thị error message chưa nhé.

**Comment by at-duyentran** [comment]
I checked this bug. The function is ok.
