### ISSUE TITLE
Atone Form: There should be a "X" button in the 1st loading screen of Atone Form

### ISSUE THREAD

**Issue by at-kiennguyen2** [netprotections/atonecon-ios#62]
### Summary (Required)
When user opens Atone Form is-case internet connection weak or can not connect to server. Atone form is loading forever and user can't close this Atone form

A suggestion that there should be a "X" button using to close the Form in the 1st loading screen if there are no requested time out.

### Description (Required)
- Open Atone Form in case internet connection is weak
- Let Atone Form open with White background

Actual result: Atone form is loading forever and user can't close this Atone form

### Acceptance Criteria (Optional)
There should be a "X" button using to close the Form in the 1st loading screen if there are no requested time out.

### References (Optional)
Please refer Android issue https://github.com/AsianTechInc/AtoneCon-Android/issues/56

**Comment by at-duyentran** [comment]
Close this issue since it's related to bug #50
